const namespace = 'listings';

export const CREATE_UPDATE_LISTING = `${namespace}/CREATE_UPDATE_LISTING`;

export const SET_LISTINGS_PAGE = `${namespace}/SET_LISTINGS_PAGE`;
export const SET_LISTINGS_SORT_ORDER = `${namespace}/SET_LISTINGS_SORT_ORDER`;
export const SET_LISTING_TABLE_SETTINGS = `${namespace}/SET_LISTING_TABLE_SETTINGS`;
export const FILTER_LISTINGS = `${namespace}/FILTER_LISTINGS`;
export const SET_LISTINGS_FILTER_PARAMS = `${namespace}/SET_LISTINGS_FILTER_PARAMS`;
export const SET_LISTINGS_SEARCH_QUERY = `${namespace}/SET_LISTINGS_SEARCH_QUERY`;

export const FETCH_LISTINGS = `${namespace}/FETCH_LISTINGS`;
export const FETCH_LISTING = `${namespace}/FETCH_LISTING`;

export const FETCH_LISTING_PROPERTY_TYPE = `${namespace}/FETCH_LISTING_PROPERTY_TYPE`;
export const FETCH_LISTINGS_BASE_PROPERTY_TYPES = `${namespace}/FETCH_LISTINGS_BASE_PROPERTY_TYPES`;

export const FETCH_LISTING_ACCOMODATION = `${namespace}/FETCH_LISTING_ACCOMODATION`;
export const UPDATE_LISTING_ACCOMODATION = `${namespace}/UPDATE_LISTING_ACCOMODATION`;

export const FETCH_LISTING_LOCATION = `${namespace}/FETCH_LISTING_LOCATION`;
export const UPDATE_LISTING_LOCATION = `${namespace}/UPDATE_LISTING_LOCATION`;

export const FETCH_LISTING_BASE_AMENITIES = `${namespace}/FETCH_LISTING_BASE_AMENITIES`;
export const UPDATE_LISTING_AMENITIES = `${namespace}/UPDATE_LISTING_AMENITIES`;
export const FETCH_LISTING_AMENITIES = `${namespace}/FETCH_LISTING_AMENITIES`;

export const FETCH_LISTING_BASE_CAPABILITIES = `${namespace}/FETCH_LISTING_BASE_CAPABILITIES`;
export const UPDATE_LISTING_CAPABILITIES = `${namespace}/UPDATE_LISTING_CAPABILITIES`;
export const FETCH_LISTING_CAPABILITIES = `${namespace}/FETCH_LISTING_CAPABILITIES`;

export const FETCH_LISTING_BASE_SERVICES = `${namespace}/FETCH_LISTING_BASE_SERVICES`;
export const UPDATE_LISTING_SERVICES = `${namespace}/UPDATE_LISTING_SERVICES`;
export const FETCH_LISTING_SERVICES = `${namespace}/FETCH_LISTING_SERVICES`;

export const UPDATE_LISTING_PHOTOS = `${namespace}/UPDATE_LISTING_PHOTOS`;
export const FETCH_LISTING_PHOTOS = `${namespace}/FETCH_LISTING_PHOTOS`;

export const UPDATE_LISTING_DESCRIPTION = `${namespace}/UPDATE_LISTING_DESCRIPTION`;
export const FETCH_LISTING_DESCRIPTION = `${namespace}/FETCH_LISTING_DESCRIPTION`;

export const FETCH_LISTING_BASE_HOUSE_RULES = `${namespace}/FETCH_LISTING_BASE_HOUSE_RULES`;
export const UPDATE_LISTING_HOUSE_RULES = `${namespace}/UPDATE_LISTING_HOUSE_RULES`;
export const FETCH_LISTING_HOUSE_RULES = `${namespace}/FETCH_LISTING_HOUSE_RULES`;

export const UPDATE_LISTING_RESERVATION_PREFERENCES = `${namespace}/UPDATE_LISTING_RESERVATION_PREFERENCES`;
export const FETCH_LISTING_RESERVATION_PREFERENCES = `${namespace}/FETCH_LISTING_RESERVATION_PREFERENCES`;

export const FETCH_LISTING_TIME_PERIODS = `${namespace}/FETCH_LISTING_TIME_PERIODS`;
export const CREATE_LISTING_TIME_PERIODS = `${namespace}/CREATE_LISTING_TIME_PERIODS`;

export const UPDATE_LISTING_PRICING = `${namespace}/UPDATE_LISTING_PRICING`;
export const FETCH_LISTING_PRICING = `${namespace}/FETCH_LISTING_PRICING`;

export const UPDATE_LISTING_STATUS = `${namespace}/UPDATE_LISTING_STATUS`;

export const UPDATE_LISTING_AVAILABILITY = `${namespace}/UPDATE_LISTING_AVAILABILITY`;
